export const CATEGORIES = [
  'Chest', 'Back', 'Shoulders', 'Legs', 'Arms', 'Abs', 'Cardio', 'HIIT', 'Yoga', 'Stretching',
]

const img = (seed) => `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=800&q=80`

export const EXERCISES = [
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    category: 'Chest',
    image: img('photo-1571019613454-1cb2f99b2d8b'),
    difficulty: 'Intermediate',
    targetMuscle: 'Chest, Triceps, Shoulders',
    equipment: 'Barbell, Bench',
    caloriesBurned: 8,
    durationMinutes: 10,
    videoUrl: 'https://www.youtube.com/results?search_query=barbell+bench+press+form',
    instructions: [
      'Lie flat on the bench with feet planted on the floor.',
      'Grip the bar slightly wider than shoulder-width.',
      'Lower the bar to mid-chest with control.',
      'Press up explosively until arms are locked out.',
    ],
  },
  {
    id: 'pushups',
    name: 'Push-Ups',
    category: 'Chest',
    image: img('photo-1598971639058-fab3c3109a34'),
    difficulty: 'Beginner',
    targetMuscle: 'Chest, Triceps, Core',
    equipment: 'None',
    caloriesBurned: 6,
    durationMinutes: 8,
    videoUrl: 'https://www.youtube.com/results?search_query=perfect+push+up+form',
    instructions: [
      'Start in a plank with hands under shoulders.',
      'Lower your chest to the floor, elbows at 45 degrees.',
      'Push back up to full extension.',
      'Keep your core tight throughout.',
    ],
  },
  {
    id: 'pullups',
    name: 'Pull-Ups',
    category: 'Back',
    image: img('photo-1598268030450-7d3e0c6c9e73'),
    difficulty: 'Advanced',
    targetMuscle: 'Lats, Biceps, Upper Back',
    equipment: 'Pull-up Bar',
    caloriesBurned: 9,
    durationMinutes: 8,
    videoUrl: 'https://www.youtube.com/results?search_query=pull+up+form',
    instructions: [
      'Hang from the bar with an overhand grip.',
      'Pull your chest toward the bar, driving elbows down.',
      'Lower with control to a full hang.',
      'Avoid swinging or kipping.',
    ],
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'Back',
    image: img('photo-1517963879433-6ad2b056d712'),
    difficulty: 'Advanced',
    targetMuscle: 'Hamstrings, Glutes, Back',
    equipment: 'Barbell',
    caloriesBurned: 10,
    durationMinutes: 12,
    videoUrl: 'https://www.youtube.com/results?search_query=deadlift+form',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot.',
      'Hinge at the hips and grip the bar just outside knees.',
      'Drive through the floor, keeping the bar close to your body.',
      'Lock out hips and knees at the top.',
    ],
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'Shoulders',
    image: img('photo-1584863231364-2edc166de576'),
    difficulty: 'Intermediate',
    targetMuscle: 'Shoulders, Triceps',
    equipment: 'Barbell or Dumbbells',
    caloriesBurned: 7,
    durationMinutes: 10,
    videoUrl: 'https://www.youtube.com/results?search_query=overhead+press+form',
    instructions: [
      'Stand with feet shoulder-width, bar at collarbone.',
      'Brace your core and press overhead.',
      'Lock arms out fully at the top.',
      'Lower with control to the starting position.',
    ],
  },
  {
    id: 'squats',
    name: 'Barbell Back Squat',
    category: 'Legs',
    image: img('photo-1534438327276-14e5300c3a48'),
    difficulty: 'Intermediate',
    targetMuscle: 'Quads, Glutes, Hamstrings',
    equipment: 'Barbell, Rack',
    caloriesBurned: 9,
    durationMinutes: 12,
    videoUrl: 'https://www.youtube.com/results?search_query=barbell+squat+form',
    instructions: [
      'Set the bar on your upper traps.',
      'Brace your core and unrack the bar.',
      'Squat down until thighs are parallel to the floor.',
      'Drive through your heels to stand.',
    ],
  },
  {
    id: 'lunges',
    name: 'Walking Lunges',
    category: 'Legs',
    image: img('photo-1571019613576-2b22c76fd955'),
    difficulty: 'Beginner',
    targetMuscle: 'Quads, Glutes',
    equipment: 'Dumbbells (optional)',
    caloriesBurned: 7,
    durationMinutes: 8,
    videoUrl: 'https://www.youtube.com/results?search_query=walking+lunges+form',
    instructions: [
      'Step forward into a long stride.',
      'Lower until both knees are at 90 degrees.',
      'Push through the front heel to step forward.',
      'Alternate legs with each step.',
    ],
  },
  {
    id: 'bicep-curls',
    name: 'Dumbbell Bicep Curls',
    category: 'Arms',
    image: img('photo-1517838277536-f5f99be501cd'),
    difficulty: 'Beginner',
    targetMuscle: 'Biceps',
    equipment: 'Dumbbells',
    caloriesBurned: 4,
    durationMinutes: 6,
    videoUrl: 'https://www.youtube.com/results?search_query=dumbbell+bicep+curl+form',
    instructions: [
      'Stand tall holding dumbbells at your sides.',
      'Curl the weights up while keeping elbows fixed.',
      'Squeeze at the top.',
      'Lower slowly to the start.',
    ],
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'Abs',
    image: img('photo-1571019613454-8e9e5b5a3e0f'),
    difficulty: 'Beginner',
    targetMuscle: 'Core',
    equipment: 'None',
    caloriesBurned: 3,
    durationMinutes: 3,
    videoUrl: 'https://www.youtube.com/results?search_query=plank+form',
    instructions: [
      'Rest on forearms and toes, body in a straight line.',
      'Brace your core and squeeze glutes.',
      'Avoid letting hips sag or pike.',
      'Hold, breathing steadily.',
    ],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'Cardio',
    image: img('photo-1517841905240-472988babdf9'),
    difficulty: 'Beginner',
    targetMuscle: 'Full Body, Calves',
    equipment: 'Jump Rope',
    caloriesBurned: 12,
    durationMinutes: 10,
    videoUrl: 'https://www.youtube.com/results?search_query=jump+rope+basics',
    instructions: [
      'Hold handles at hip height, wrists doing the work.',
      'Jump just high enough to clear the rope.',
      'Land softly on the balls of your feet.',
      'Keep a steady rhythm.',
    ],
  },
  {
    id: 'burpees',
    name: 'Burpees',
    category: 'HIIT',
    image: img('photo-1517836357463-d25dfeac3438'),
    difficulty: 'Intermediate',
    targetMuscle: 'Full Body',
    equipment: 'None',
    caloriesBurned: 14,
    durationMinutes: 8,
    videoUrl: 'https://www.youtube.com/results?search_query=burpee+form',
    instructions: [
      'Drop into a squat and place hands on the floor.',
      'Kick feet back into a plank.',
      'Return feet to the squat, then jump up explosively.',
      'Repeat at a steady pace.',
    ],
  },
  {
    id: 'downward-dog',
    name: 'Downward Facing Dog',
    category: 'Yoga',
    image: img('photo-1544367567-0f2fcb009e0b'),
    difficulty: 'Beginner',
    targetMuscle: 'Hamstrings, Shoulders, Back',
    equipment: 'Yoga Mat',
    caloriesBurned: 3,
    durationMinutes: 5,
    videoUrl: 'https://www.youtube.com/results?search_query=downward+dog+yoga',
    instructions: [
      'Start on hands and knees.',
      'Lift hips up and back, forming an inverted V.',
      'Press heels toward the floor.',
      'Relax your neck and breathe deeply.',
    ],
  },
  {
    id: 'hamstring-stretch',
    name: 'Standing Hamstring Stretch',
    category: 'Stretching',
    image: img('photo-1518611012118-696072aa579a'),
    difficulty: 'Beginner',
    targetMuscle: 'Hamstrings',
    equipment: 'None',
    caloriesBurned: 1,
    durationMinutes: 3,
    videoUrl: 'https://www.youtube.com/results?search_query=standing+hamstring+stretch',
    instructions: [
      'Stand tall and extend one leg forward, heel down.',
      'Hinge at the hips, keeping your back flat.',
      'Hold the stretch without bouncing.',
      'Switch legs and repeat.',
    ],
  },
]
